import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { dbConnect } from "@/service/mongo"
import "./globals.css";
import Sidebar from "./Sidebar";
import Headers from "./headers/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConnect();
  return (
    <html lang="en" >
      <body className={inter.className}>
        <main className="flex min-h-screen bg-gray-900">
          <Sidebar />
          <div className="relative h-full min-h-screen transition-all duration-200 ease-in-out xl:ml-68 rounded-xl w-full flex flex-col">
            <Headers />
            <div className="flex-shrink flex-1 bg-white h-full mx-6 mb-6 rounded-xl">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
